// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"about.en.mdx": () => import("../content/docs/about.en.mdx?collection=docs"), "about.ja.mdx": () => import("../content/docs/about.ja.mdx?collection=docs"), "basic-diagram.en.mdx": () => import("../content/docs/basic-diagram.en.mdx?collection=docs"), "basic-diagram.ja.mdx": () => import("../content/docs/basic-diagram.ja.mdx?collection=docs"), "cli.en.mdx": () => import("../content/docs/cli.en.mdx?collection=docs"), "cli.ja.mdx": () => import("../content/docs/cli.ja.mdx?collection=docs"), "custom-integration.en.mdx": () => import("../content/docs/custom-integration.en.mdx?collection=docs"), "custom-integration.ja.mdx": () => import("../content/docs/custom-integration.ja.mdx?collection=docs"), "examples.en.mdx": () => import("../content/docs/examples.en.mdx?collection=docs"), "examples.ja.mdx": () => import("../content/docs/examples.ja.mdx?collection=docs"), "index.en.mdx": () => import("../content/docs/index.en.mdx?collection=docs"), "index.ja.mdx": () => import("../content/docs/index.ja.mdx?collection=docs"), "interactive-features.en.mdx": () => import("../content/docs/interactive-features.en.mdx?collection=docs"), "interactive-features.ja.mdx": () => import("../content/docs/interactive-features.ja.mdx?collection=docs"), "json-reference.en.mdx": () => import("../content/docs/json-reference.en.mdx?collection=docs"), "json-reference.ja.mdx": () => import("../content/docs/json-reference.ja.mdx?collection=docs"), "multi-file.en.mdx": () => import("../content/docs/multi-file.en.mdx?collection=docs"), "multi-file.ja.mdx": () => import("../content/docs/multi-file.ja.mdx?collection=docs"), "organizing-groups.en.mdx": () => import("../content/docs/organizing-groups.en.mdx?collection=docs"), "organizing-groups.ja.mdx": () => import("../content/docs/organizing-groups.ja.mdx?collection=docs"), "styling-themes.en.mdx": () => import("../content/docs/styling-themes.en.mdx?collection=docs"), "styling-themes.ja.mdx": () => import("../content/docs/styling-themes.ja.mdx?collection=docs"), "vendor-icons.en.mdx": () => import("../content/docs/vendor-icons.en.mdx?collection=docs"), "vendor-icons.ja.mdx": () => import("../content/docs/vendor-icons.ja.mdx?collection=docs"), "yaml-reference.en.mdx": () => import("../content/docs/yaml-reference.en.mdx?collection=docs"), "yaml-reference.ja.mdx": () => import("../content/docs/yaml-reference.ja.mdx?collection=docs"), "netbox/api.en.mdx": () => import("../content/docs/netbox/api.en.mdx?collection=docs"), "netbox/api.ja.mdx": () => import("../content/docs/netbox/api.ja.mdx?collection=docs"), "netbox/index.en.mdx": () => import("../content/docs/netbox/index.en.mdx?collection=docs"), "netbox/index.ja.mdx": () => import("../content/docs/netbox/index.ja.mdx?collection=docs"), "netbox/visualization.en.mdx": () => import("../content/docs/netbox/visualization.en.mdx?collection=docs"), "netbox/visualization.ja.mdx": () => import("../content/docs/netbox/visualization.ja.mdx?collection=docs"), }),
};
export default browserCollections;